--- # yum
- hosts: all 
  sudo: yes
  user: deploy 
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install a package
    yum: pkg={{ item }} state=latest
    with_items:
    - telnet
    - lynx
    - git
    - wget
    - curl
    - zsh
